### ISSUE TITLE
Unable to connect to Client when tying to connect to google.

### ISSUE THREAD

**Issue by dynamicskies** [d8ahazard/Phlex#162]
Cant link google acct. when i try to link google i get this message.

> unable to connect to Client at http://My.plex.IP/Phlex, please check the setting for 'Public Address' in the Phlex UI.

but if i click on amazon it works.

i port forward  1088
Destination Ports 1088
TCP Any -> 1088
cause port 80 was being used
not sure if i did that wrong.

Remote access is on and works in plex.

**Comment by RobotRamone** [comment]
Same with me and Google.  Haven't tried Amazon.

**Comment by bcb2000** [comment]
I am experiencing the same.  I have been adding my comments in issue #132

**Comment by dynamicskies** [comment]
Ill subscribe to yours hopfully you figure it out cause I have no clue .

**Comment by RobotRamone** [comment]
We had a different thread going about something else --- that turned into this issue.
After doing some research the issues I'm having might have something to do with MyApache Binding.  Not sure.  But somehow the system bound to default settings rather than adopting the new port settings. 

However, I'm flying blind too....

**Comment by RobotRamone** [comment]
I can play music on my Google Home from the computer I'm running my Plex server from.  But the voice commands don't work, nor does Google Home recognize the link.  It's pretty odd.  The individual services seem to be working, but the sum of the parts don't make a whole.

**Comment by dynamicskies** [comment]
> I can play music on my Google Home from the computer I'm running my Plex server from. Plex and Phlex are linked. But the voice commands don't work through Phlex, nor does Google Home recognize the link. I can run music through the computer, but not through my TV's Plex Samsung app. It's pretty odd. The individual services seem to be kind of working, but the sum of the parts don't make a whole.

 thats weird that your samsung plex app doesnt work maybe its a bad app. I would make sure plex is working 100%. I don't have any trouble with plex its 100% working on all my apps. I don't use the tv app my tv smart tv part is way to slow.
I'm going to try and install it to another computer just to see if it has something to do with my computer  
didn't think of this till i was driving to work so ill have to wait to do that till tonight.

**Comment by dynamicskies** [comment]
also when i looked in Plex settings  under devices connected in plex is there 7 times is that normal?
should i delete all  and reconnect or all but one? not sure why there is so many plex showing up there.

**Comment by dynamicskies** [comment]
sorry miss understood

**Comment by dynamicskies** [comment]
installed on another computer and got the same thing

unable to connect to Client at http://My.plex.IP/Phlex, please check the setting for 'Public Address' in the Phlex UI. 
so i dont know maybe its somthing to do with my router

**Comment by bcb2000** [comment]
Updates:
I had a brief success linking my Google account this morning.  What had changed between last week and this, was I had a new Plex 'friend'.  So, when I tried to link Google, it worked, assistant.google.com came up and I was able to link accounts.  However, the only server then showing in Phlex was my friend's server.  My server was not shown.

Since then, I unfriended the friend, and reset Phlex (by deleting config.ini.php) and once again, I cannot link Google now.  So I conclude from this, that something specific about my server is causing problems for the Google Account linking process.

@d8ahazard , please can you check your api server logs and see if you can spot the difference between my successful account linking (around 2000UTC 24-Oct) and the subsequent ones (around 2020UTC 24-OCT).  My public IP is 101.112.193.174.

Thanks!

**Comment by bcb2000** [comment]
Solved it!

The link here:
https://support.plex.tv/hc/en-us/articles/204604227-Why-can-t-the-Plex-app-find-or-connect-to-my-Plex-Media-Server-

suggested:
1. Sign out of your Plex account in both the app and Plex Media Server
2. Sign into your account in the Server
3. Then sign into your account in the Plex app

I followed this sequence, and now Phlex is connected to my account and can see my server.

**Comment by dynamicskies** [comment]
Cool cant wait to try this when I get home. Do i have to sign out of all my plex apps or just the phlex app. Cause i have a crap load of things login to plex.

**Comment by RobotRamone** [comment]
The Phlex logo shows up again on my Plex app running on my Samsung TV.

But how do I get my Google Home to recognize voice commands? 

Every time I click on Link to Google in Pflex --- this comes up.

 

Unable to connect to Client at http://xx.xxx.xxx.xxx/Phlex, please check the setting for 'Public Address' in the Phlex UI.

Not sure why my Public IP address doesn’t work.  There used to be a radio button in Phlex to use the Public IP.

It’s no longer there.

 

Mark

**Comment by gtmanfred** [comment]
This worked for me too, but I did also nuke the whole phlex directory.

I am using the docker image.

**Comment by bcb2000** [comment]
In detail:

- I logged into my Plex server http://127.0.0.1:32400/
- I unlinked my account for the server
- I stopped and started my Plex server
- I linked my my server back to my Plex Account
- I stopped my Apache web server for Phlex (the config.ini.php file was locked by the web server process)
- I deleted all my config.ini.php in Phlex
- I started my Apache web server for Phlex
- I logged in to Phlex
- I linked my Google account

I now have voice control from my Google home or my Google Pixel phone.  e.g. "Ok Google... Tell Flex TV to show Blade Runner"

**Comment by gtmanfred** [comment]
if you have an api key already, you will want to save the config.ini.php, and not delete it

**Comment by dynamicskies** [comment]
didnt work for me . could it be that i have a friend acct linked still?
not sure if i did first part right?
I logged into my Plex server http://127.0.0.1:32400/
I unlinked my account for the server under settings , server tab and sign out ?

I stopped and started my Plex server by right clicking andf telling it  to close it.

I linked my my server back to my Plex Account under settings and server tab  claim server?

I stopped my Apache web server for Phlex (the config.ini.php file was locked by the web server process)

I deleted config.ini.php in Phlex
I started my Apache web server for Phlex
I logged in to Phlex
I linked my Google account

**Comment by Praenei** [comment]
For what it's worth I had this issue.  Key things I changed/checked to get it working for me were -

1) Made sure that openssl was turned on in XAMPP (Windows / PHP 7.0.24 version for me).  This involved editing the php.ini (use the Config button on the XAMPP control panel) to search for & remove the semi-colon in front of 'extension=php_openssl.dll'.  If you are using XAMPP that should be all you need to change in the PHP configuration.
2) Reconfigured to listen on a different port.  In my case I edited the http,conf file (again from Configure on XAMPP control panel) so that Listen 80 became Listen 125.  Also had to go into my Router settings & port forward port 125 to 125. Not sure if this last bit is needed.  
3) I called the folder beneath htdocs 'phlex' rather than the name in the zip of 'Phlex-master'.  Not sure if this affected anything but it was something I changed before it started working & I did read a comment on one of the forums that Phlex didn't like dashes in user names!
4) Very important - make sure that it is accessible to the outside world.  This can be done by using a site like http://canyouseeme.org/ & entering the port number you chose. This will also give you the external ip address that you'll need to step 5)
5) In the Phlex settings on the web app make sure that the public address is in the form 11.11.11.11:125/phlex.  In other words no 'http://' at the start & no '/' at the end
6) Hopefully you can now run the Test Connectivity option & get a successful message.

Good luck.

**Comment by RobotRamone** [comment]
This gets me closer!  

Should the listen to address be the public or private IP?

 

Mark

**Comment by RobotRamone** [comment]
BOOM!

 

Answered my own question.  Dude Praenei you’re awesome!

The Listen To address is the private IP.

I didn’t have my port listed in the Phlex UI settings Public IP address section.  AND deleting the http:// finally got me to my Google login screen.

 

Thanks so much.

 

Mark

**Comment by RobotRamone** [comment]
So I’m getting closer.  But the Google Home app on my Pixel XL says I’m not linked to Flex.  When I click on the link --- nothing happens.

I’m unable to ask Google to Talk to Flex TV.

 

Thoughts?

**Comment by dynamicskies** [comment]
>  For what it's worth I had this issue. Key things I changed/checked to get it working for me were -
> 
> Made sure that openssl was turned on in XAMPP (Windows / PHP 7.0.24 version for me). This involved editing the php.ini (use the Config button on the XAMPP control panel) to search for & remove the semi-colon in front of 'extension=php_openssl.dll'. If you are using XAMPP that should be all you need to change in the PHP configuration.
> Reconfigured to listen on a different port. In my case I edited the http,conf file (again from Configure on XAMPP control panel) so that Listen 80 became Listen 125. Also had to go into my Router settings & port forward port 125 to 125. Not sure if this last bit is needed.
> I called the folder beneath htdocs 'phlex' rather than the name in the zip of 'Phlex-master'. Not sure if this affected anything but it was something I changed before it started working & I did read a comment on one of the forums that Phlex didn't like dashes in user names!
> Very important - make sure that it is accessible to the outside world. This can be done by using a site like http://canyouseeme.org/ & entering the port number you chose. This will also give you the external ip address that you'll need to step 5)
> In the Phlex settings on the web app make sure that the public address is in the form 11.11.11.11:125/phlex. In other words no 'http://' at the start & no '/' at the end
> Hopefully you can now run the Test Connectivity option & get a successful message.
> Good luck.
> 

 did everything but semi-colon and ill check the http part thanks for the reply . cant wait to try this tonight.

**Comment by RobotRamone** [comment]
I’m limping through.  The voice recognition is now working from Google Home.  

However, the Flex TV service is unable to identify the libraries I’m requesting.

 

What I’m not clear on is which device I should be casting to on Google Home, Phlex, and Plex Media Server.

My main goal is to play music on my Google Home via my Plex Media Server --- which is linked to a HDD I store all of my files on.

This may be better suited for a different thread.  But I’ve search high and low on YouTube videos and threads to no avail.  All of the YouTube tutorials assume every connection is working and things are set up properly.  There’s little information on step by step instructions on what exactly the settings need to be for communication to work.

**Comment by Praenei** [comment]
Good to hear that you're making some progress.  I'm not running from Google Home but from a Google Nexus 5X so cannot answer the bit about what you should be casting to but I'd imagine it would be your Home.  Does its name appear above the Cast icon on Phlex?  I had issues getting my Chromecasts to appear.  In the end I had to ensure that the Cast devices button, or something like that,  (sorry, not got it in front of me at the moment but on the second tab of options on Phlex)  was turned on.  It did seem to take some time to recognise what was on the network even after clicking Rescan, so leave it 5 mins.  

I'm also running from a NAS drive & needed to make sure that it appeared on the second tab of Phlex settings but again took time to appear & seemed to bit a bit flakey.  Once it was working though it seemed to stay working.  Maybe try the experimental button at the bottom of that page if you have problems.  Also worth having a look at the log files (4th tab on Phlex settings) to try & identify any issues there.  

Final thought, have you opened up the port of your Plex on your router (Porting forwarding) so that you can get to itfrom outside of your network?  Again try canyouseeme.org with your externl ip address & your Plex port.  I'd imagine that Phlex would need it but that might be a complete red herring.

Good luck!

**Comment by RobotRamone** [comment]
In the Phlex UI, under the Plex > General > Playback Servers, the only servers showing up are friends servers and the Plex Cloud.  

I don’t use the Plex Cloud, which is probably why Phlex can’t find my libraries.  However, why doesn’t my local Plex Media Server show up?

**Comment by dynamicskies** [comment]
my post got **hijacked** lol.  
thanks Praenei  i was able to connect to google. it was the http that was stping me i think.
Now i cant see servers in  phlex under plex tab list when before i was able to . when i hit blue box says its connected but when i say talk to phlex google says it cant help me with that. any ideas

**Comment by dynamicskies** [comment]
now it shows servers i didnt change anything but there is 2 of each

**Comment by Praenei** [comment]
Sorry dynamicskies but you've reached the limit of my knowledge. I too am still finding that things quite often aren't connecting. In my case I'm only playing around with phlex as I cannot install it on my NAS server (doesn't support PHP 7+ yet) & I don't want to have to leave my pc left on. Best of luck going forward though & hopefully you'll get to the bottom of it soon

**Comment by dynamicskies** [comment]
Thanks . I think im good now some bugs with phlex now i think now. I cob ecter a second acct by siging in another browser and loging into my wifes acct.  The bugs i have is that phlex keeps turning my tv back on i have to turn off my tv 3 times before it stays off never did that before phlex. Otger bug is when my wife uses it  doesnt want to do what she asks everytime. Dont know if this all has to do with having two accts connected to phlex.

Be sodes that im all good thanks for your help

**Comment by dynamicskies** [comment]
Thanks . I think im good now some bugs with phlex now i think now. I connected  a second acct by singing in another browser and loging into my wifes acct.  The bugs i have is that phlex keeps turning my tv back on i have to turn off my tv 3 times before it stays off never did that before phlex. Otger bug is when my wife uses it  doesnt want to do what she asks everytime. Dont know if this all has to do with having two accts connected to phlex.

Be sodes that im all good thanks for your help

**Comment by blaker78** [comment]
so I am still having the issue of not being able to get to the google sign in page.  I followed Praenei suggestions but now when I test my connection instead of it saying "Connection to xxx.xxx.xxx.xxx:5666/phlex failed" it now says "successConnection to xxx.xxx.xxx.xxx:5666/phlex failed"

anyone see that successConnection before?

**Comment by robz112** [comment]
I too have been all over the forums, and have tried just about every suggestion mentioned. After hours and hours of doing that, i still get the failed connection message and can't connect to google. I have the ports forwarded and verified that they are open and Phlex can see my Plex server. Only hiccup is that whole linking google thing. Anyone have any other ideas i can try? Let me know if you need logs/more info. From what i read this issue seems to happen a bit.

**Comment by fun4stuff** [comment]
It's really buggy. I don't know if this will be my head help, but I was having the same problems (running phlex in a docker know synology) and I solved by logging out of phlex from my browsers, clearing browser cookies, uninstalling phlex, reinstalling. Unlinking and relinking flex from Google in Google assistant app. Then went back into phlex settings and clicked link with Google and it worked. This was in Firefox, btw. Was having trouble in chrome. 

I've had to do this sequence two times so far.... If phlex crashes or after some time passes I get an error from Google home which tells me I have to redo all this.

**Comment by d8ahazard** [comment]
Hi, thanks for the feedback.

This issue has either been fixed in the current /beta branch, or is slated for revisal/revision in the forthcoming V2 release.

As such, I'll be closing this issue to help focus on outstanding issues and features yet to be addressed in the new codebase.

Feel free to follow the progress in the /beta branch, and be sure to get set up by adding the new cast plugin to your local Plex server.

https://github.com/d8ahazard/Cast.bundle

Keep an eye on the forum for the release of FlexTV 2.0!

**Comment by RobotRamone** [comment]
Just so I am informed…are you no longer pursuing the original design of your app? 

I ask so I know what to clean off my computer.

 

Mark

**Comment by d8ahazard** [comment]
I am still developing the application.

The /master branch is no longer being developed.

New work will be committed to /beta until I feel it's "ready" for public
consumption, at which time, it'll become the main branch again.

You're welcome to use the /beta branch now, just understand that it's under
development so things may not work or be broken entirely.

**Comment by RobotRamone** [comment]
Cool man.  I’m glad you’re taking another run at it.  I bet it was more popular than you anticipated.

I look forward to the beta.

**Comment by jpdumal** [comment]
This isn't fixed. I can't make this work on my Ubuntu 16.04 server. I can access Phlex from the outside but still can't manage to link with Google. I've tried all the suggestions mentionned in the comments without any success. I've intalled Xampp and Phlex on a Windows 10 machine and was able to link with Google. What I am missing? I would prefer Phlex to run on my server. Thank you!
