### ISSUE TITLE
ERROR: Unauthenticated access detected. Originating IP

### ISSUE THREAD

**Issue by damianodonoghue** [d8ahazard/Phlex#266]
## ISSUE TEMPLATE

Please read over the [Notes/FAQ](Notes-FAQ) and [networking](Talking-To-The-Outside-World) sections before reporting an issue.

If your issue is not resolved, try to fill out the following as completely as possible. I'm not going to delete issues just because forms aren't filled out completely, but I will if you provide me no information whatsoever.

If submitting a feature request, these are not required.

My Issue is
I've never got this to work. First I tried docker and it wouldn't see chromecasts so I created a windows 10 xampp machine. Now I can see chromecasts but when I ask phlex It won't play. It searches and returns the artists but it never starts. I can even ask it whats on deck it just won't play. I lost my config but relinked my account with no joy. The logs show

Thu, 21 Dec 2017 08:02:40 +0100api.php
Invalid API Token, forcing logout.
Thu, 21 Dec 2017 08:02:40 +0100api.php
ERROR: Unauthenticated access detected. Originating IP
Thu, 21 Dec 2017 08:02:40 +0100api.php
Sorry, couldn't validate user.
Thu, 21 Dec 2017 08:02:39 +0100api.php
INCOMING REQUEST!!

Any help would be really appreciated thanks!

#### 1. On what OS are you running Phlex?
Windows 10
#### 2. Are you using a new instance of XAMPP, or an existing webserver?
XAMPP
#### 2b. If not XAMPP, what WebServer stack are you using?
NA
#### 3. Have you enabled the sockets module and ensured PHP has write-access to the directory containing Phlex?
Yes
#### 4. Have you followed the (networking)[Talking-To-The-Outside-World] section?
Yes
#### 5. If you're having issues with a specific command, please note the timestamp in the web UI, and take a look at Phlex and Phlex_error.log files.  Paste anything that looks related as well.

*BE SURE TO CHANGE ANY LINES CONTAINING API TOKENS OR OTHER PERSONAL IDENTIFYING INFORMATION*

#### 6. What are the last six digits of your server's API Token? (Settings -> Phlex)
c094da

**Comment by Arthrax** [comment]
I am having the same issue recently. I can write command on the browser console to play videos but whenever I use Google Assistant (Google Home and in Assistant app), I get this error in the browser console log: 

"Thu, 21 Dec 2017 20:42:16 -0500api.php
Invalid API Token, forcing logout.
Thu, 21 Dec 2017 20:42:16 -0500api.php
ERROR: Unauthenticated access detected. Originating IP"

and in the assistant app I am told to report this:  "along with the message "Error 22: The requested URL returned error: 417 Expectation Failed"

Last six digits of API: 5a30e8

**Comment by damianodonoghue** [comment]
I think this is the same as issue https://github.com/d8ahazard/Phlex/issues/252 .

**Comment by damianodonoghue** [comment]
Can anyone help? I'm pulling my hear out!

**Comment by Jon87** [comment]
I had this error too.

I fixed it by allowing unauthenticated access to plex from inside my network.

Plex settings -> Server -> Network-> show advanced.

Set "List of IP addresses and networks that are allowed without auth" to have your home network range. For me this was "192.168.0.0/24"

You could just set your phlex server and chromecasts etc if you're worried about security but I'm not too bothered about my internal network having access. HTH

**Comment by damianodonoghue** [comment]
Hi Jon, thanks for the info. I tried this thinking it was what the error pointed to myself also but it didn't make a difference. I double checked when I read your post and it was set in there with no luck. I think the problem is with the google action because if I start the xampp and go in and relink my account plex will play one think for me and then won't accept any commands. I think it has something to do with account linking. Thanks for the tips and any other suggestions would be great.

**Comment by Arthrax** [comment]
Unfortunately it didn't work for me either. I looked at the logs and it looks like the API number that my google account is sending is not the same as the one stored in Phlex. I never updated in the first place but it changed some how. I did relink my google account multiple times but it's not changing 😞 I even did a fresh install and relinked again, but still no luck.

**Comment by asdub** [comment]
Having the same issue. 
However, I have managed to get things working again by removing access from Phlex in my Google account then relinking.
I'm still not receiving the correct responses - "I'll try...etc". But the commands are working.

**Comment by d8ahazard** [comment]
I'd try the beta branch for now - this functionality has been heavily re-worked in the new release. While it's not finished yet, it has already been addressed in the recode, and as such, I'm going to close this issue to keep things straight for dev purposes.

You'll also need to install the cast plugin on a local Plex server.  https://github.com/d8ahazard/Cast.bundle
