### ISSUE TITLE
Phlex responds with "Okay, I'll work on that" to all commands

### ISSUE THREAD

**Issue by nickmodernized** [d8ahazard/Phlex#59]
Great software!

Except...and I'm not sure when this broke, but it seems like two git pulls ago...Phlex isn't responding to my voice commands.  It finds all the chromecasts, all the settings appear correct, and Google Home says "Okay, here's Flex TV" -- but then Phlex responds with an "Okay, I'll work on that" or an "Okay, I'll see if I can do that" with nothing else happening.  It seems like the command isn't getting from remote to my local.

How can I best provide logs to troubleshoot this issue?

**Comment by anick08** [comment]
I'm having the same issue.

**Comment by d8ahazard** [comment]
shoot me an email at my debug address (donate.to.digitalhigh@gmail.com) detailing the email address you're using to register with Phlex, as well as your public address for your Phlex install and Phlex.log and Phlex_error.log files.

**Comment by nickmodernized** [comment]
Sent!

**Comment by hermy65** [comment]
Running into the same issue as those above, should i send logs as well?

**Comment by mbze430** [comment]
I am also seeing this problem A LOT.  The webui end of Phlex doesn't show I actually issued the commands.  So I don't know if the a log will be helpful.  but let me know.

Last night I kept telling, "Hey Google, Ask Flex Tv to play The Originals".  It keeps responding "Okay, I'll work on that".  But checking the webui it never executed the command, "Hey Google, Ask Flex Tv to play The Originals"

**Comment by d8ahazard** [comment]
All - the issue here for "Okay, I'll work on that" is more than likely your APIToken having been reset.  This happens if you remove config.ini.php in the Phlex directory.  

Once Phlex is installed - you need to do a GIT PULL, or extract the contents of the .zip (if downloaded as a zip) over the existing directory.  

Removing the config.ini.php will reset your APIToken, which breaks the linkage between Phlex and Google.

To fix it, you need to re-register your server from the web UI, then unlink and relink Phlex in the Google home app.  

@mbze430 - Do an update once, I think your playback commands are failing because of an error I just fixed.

**Comment by nickmodernized** [comment]
So - I was able to get it by replacing the "apiKey" variable in my
config.ini.php file with the one d8ahazard sent me.  I also had to upgrade
to PHP7...I don't remember actually deleting the config.ini.php file, but I
wonder if doing some sort of git pull at the wrong time had caused it to
get replaced or re-register somehow?

Regardless, seems to be working now.  It looks like I'll still get the
response the "Phlex TV is not responding", but it seems that it functions
regardless of that message.

I'm wondering if that message comes up because of some sort of timing issue
when it is searching for a new file to play.

Nick

**Comment by nickmodernized** [comment]
Does anybody else have any issues with this?  If your API key is correct, it seems to be working.  If not, I'm happy to close the ticket...

**Comment by d8ahazard** [comment]
I think I see an issue where the DB was duplicating user records on re-registration.  This should be fixed now, if you guys want to try re-linking and see if that gets you going.

**Comment by d8ahazard** [comment]
@nickmodernized @mbze430 @hermy65 Any improvement with this and the server changes and/or the latest commits?

**Comment by mbze430** [comment]
I haven't tried for the past week or so.

Will try this weekend and report back.
 

    On Wednesday, July 26, 2017 4:59 PM, d8ahazard <notifications@github.com> wrote:
 

 @nickmodernized @mbze430 @hermy65 Any improvement with this and the server changes and/or the latest commits?—
